In [1]:
# Importing dependencies

from learntools.core import binder
import numpy as np

binder.bind(globals())

from learntools_ex import *

print("Setup Complete")

Setup Complete


## **Questions**

### **IMPORTANT**: You **don't** have to delete any `q{n}.check()` or `q{n}.hint()` or `q{n}_sol = question_{n}()`. Please make sure that the function name and function signature match the question and the example given. Additionally, all functions should be runnable or your solution will not be evaluated.

## **Q1:** Create a one-dimensional NumPy array of the numbers from 5 to 905, counting by 10?

In [52]:
def question_1():
    return np.arange(5, 905, 10)


q1_sol = question_1()
q1.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q2**: Create the same NumPy array using a Python range and a list? (Hint: create a list)

In [12]:
def question_2():
    return list(range(5, 906, 10))

q2_sol = question_2()
print(q2_sol)  # Optional: to verify the output


[5, 15, 25, 35, 45, 55, 65, 75, 85, 95, 105, 115, 125, 135, 145, 155, 165, 175, 185, 195, 205, 215, 225, 235, 245, 255, 265, 275, 285, 295, 305, 315, 325, 335, 345, 355, 365, 375, 385, 395, 405, 415, 425, 435, 445, 455, 465, 475, 485, 495, 505, 515, 525, 535, 545, 555, 565, 575, 585, 595, 605, 615, 625, 635, 645, 655, 665, 675, 685, 695, 705, 715, 725, 735, 745, 755, 765, 775, 785, 795, 805, 815, 825, 835, 845, 855, 865, 875, 885, 895, 905]


## **Q3**: How might you create a NumPy array of the capital letters, A-Z? (Hint: Ever heard of string.ascii_uppercase?)

In [22]:
import string

def question_3():
    return np.array(list(string.ascii_uppercase))

q3_sol = question_3()


## **Q4**: Create a ten-element NumPy array object of all zeros and a six-element NumPy array object of all ones.

In [21]:
def question_4() -> tuple:
    sol1 = np.zeros(10)
    sol2 = np.ones(6)
    return (sol1, sol2)

q4_sol_1, q4_sol_2 = question_4()

## **Q5**: Given an 2-D array, print the third column.

In [23]:
input = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])


def question_5(input):
    return input[:, 2]


q5_sol = question_5(input)

## **Q6**: Create an array of the shape (3, 4), filled with 64-bit integer zeros.

In [ ]:
def question_6():
    return np.zeros((3, 4), dtype=np.int64)

q6_sol = question_6()


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## **Q7**: Split an array into 3 equal-sized sub-arrays.

In [25]:
input = np.arange(7, 34, 1).reshape(9, 3)



def question_7(input):
    return tuple(np.split(input, 3))


q7_sol_1, q7_sol_2, q7_sol_3 = question_7(input)
q7.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q8**: Return the last 2 elements by each of the first rows of the (3,4) array. 

In [27]:
input = np.arange(1, 13, 1).reshape(3, 4)


def question_8(input):
    return input[:2, -2:]


q8_sol = question_8(input)
q8.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q9**: Return how many elements are greater than 5 in an array.

In [29]:
input = np.arange(1, 13, 1).reshape(3, 4)


def question_9(input):
    return np.sum(input > 5)


q9_sol = question_9(input)
q9.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q10**: Delete the second column from an array and insert the following new column in the same place.

In [ ]:
input = np.array([[34, 72, 33], [82, 22, 32], [59, 84, 10]])
insert_data = np.array([[37, 37, 37]])

def question_10(input, insert_data):
    
    input_modified = np.delete(input, 1, axis=1)
    result = np.insert(input_modified, 1, insert_data[:, 0], axis=1)

    return result

q10_sol = question_10(input, insert_data)
q10.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q11**: Compute the Euclidean distance between each pair of consecutive points in a given 2D NumPy array and append the result as a new column.

Euclidian distance between two points $(x_1, y_1)$ and $(x_2, y_2)$ is $\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$.  

In [74]:
input = np.array([[1, 2], [4, 6], [7, 8], [10, 10]])
def question_11(input):
    diffs = input[1:] - input[:-1]

    # Tính khoảng cách Euclidean
    distances = np.sqrt(np.sum(diffs**2, axis=1))

    # Thêm khoảng cách vào vị trí tương ứng: gán cho dòng đầu tiên của từng cặp
    # Do dòng cuối không có điểm tiếp theo ⇒ pad bằng np.nan
    distances = np.append(distances, np.nan).reshape(-1, 1)

    # Ghép vào input
    result = np.hstack((input, distances))

q11_sol = question_11(input)
q11.check()

AttributeError: 'NoneType' object has no attribute 'dtype'

## **Q12**: Remove consecutive duplicates from a NumPy array.

In [43]:
input = np.array([[1, 1], [2, 1], [3, 3], [3, 3], [2, 1], [1, 1]])


def question_12(input):
    # Compare current rows to the previous ones
    # The first row is always kept
    mask = np.any(input[1:] != input[:-1], axis=1)
    
    # Prepend True to keep the first row
    mask = np.insert(mask, 0, True)
    
    return input[mask]


q12_sol = question_12(input)
q12.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q13**: Given a 2D NumPy array representing strokes, normalize all rows by subtracting the mean of each column and dividing by the standard deviation, but avoid division by zero.
$X_{\text{normalized}} = \frac{X - \mu}{\sigma}$

In [44]:
input = np.array([[10, 20, 30], [15, 24, 33], [8, 18, 29], [14, 22, 32]])

def question_13(input):
    # Compute column-wise mean and std
    col_mean = np.mean(input, axis=0)
    col_std = np.std(input, axis=0)
    
    # Avoid division by zero by setting zero std to 1
    col_std[col_std == 0] = 1
    
    # Normalize
    normalized = (input - col_mean) / col_std
    return normalized


q13_sol = question_13(input)
q13.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q14**: Delete the second column from an array and insert a new column at the same position where each value is the sum of its corresponding row.

In [58]:
input = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


def question_14(input):
    row_sums = np.sum(input, axis=1).reshape(-1, 1)  # Tổng theo hàng, dạng cột
    input_wo_col = np.delete(input, 1, axis=1)       # Xoá cột thứ 2 (index 1)
    result = np.insert(input_wo_col, 1, row_sums, axis=1)  # Chèn cột tổng vào vị trí 1
    return result

q14_sol = question_14(input)
q14.check()

<IPython.core.display.Javascript object>

<span style="color:#cc3333">Incorrect:</span> Incorrect value for `q14_sol`: `array([[ 1,  6, 15, 24,  3],
       [ 4,  6, 15, 24,  6],
       [ 7,  6, 15, 24,  9]])`

## **Q15**: Extract Unique Characters from a NumPy Array of Strings
Given a 1D NumPy array of strings, extract all unique characters present in the array and sort by their ASCII values.

In [66]:
input = np.array(["hello", "world", "numpy", "rocks"])


def question_15(input):
    flat_list = input.flatten().tolist()
    
    # Gộp toàn bộ thành một chuỗi
    combined = ''.join(flat_list)
    
    # Lấy danh sách ký tự duy nhất theo ASCII
    unique_chars = sorted(set(combined))
    
    # Trả về mảng NumPy kiểu chuỗi ký tự Unicode độ dài 1
    return np.array(unique_chars, dtype='<U1')

q15_sol = question_15(input)
q15.check()

<IPython.core.display.Javascript object>

<span style="color:#cc3333">Incorrect:</span> Incorrect value for `q15_sol`: `array(['c', 'd', 'e', 'h', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 'u',
       'w', 'y'], dtype='<U1')`

## **Q16**: Generate a dictionary that maps each unique character to a unique index starting with 0, sorted by ascending ASCII value.

In [75]:
input = np.array(["a", "b", "c", "d", "a", "c", "e"])


def question_16(input):
    unique_chars = sorted(set(input))  # Step 1 & 2
    return {char: idx for idx, char in enumerate(unique_chars)} 


q16_sol = question_16(input)
q16.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q17**: Convert a List of 2D traces into a Single NumPy Array
Given a list of 2D traces (each being a NumPy array of shape `(N, 2)`), stack them into a single NumPy array.

In [76]:
input = [np.array([[1, 2], [3, 4]]), np.array([[5, 6], [7, 8], [9, 10]])]


def question_17(input):
    return np.vstack(input)


q17_sol = question_17(input)
q17.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q18**: Convert a List of Text Labels into a NumPy Array of Integer Encodings
Given a vocabulary dictionary and a string of space-separated labels, convert the text into a NumPy array of indices.

In [78]:
input = {
    "hello": 0,
    "numpy": 1,
    "rocks": 2,
    "world": 3,
    "python": 4,
    "data": 5,
    "science": 6,
}

labels = "hello rocks"



def question_18(input, labels):
    return np.array([input[label] for label in labels.split()])

q18_sol = question_18(input, labels)
q18.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q19**: Extract Non-Zero Differences from an Array
Given a NumPy array of first-order differences, extract only non-zero differences using masking.

In [81]:
input = np.array([[3, 4], [0, 0], [-2, 1]])


def question_19(input):
    mask = np.any(input != 0, axis=1)
    return input[mask]


q19_sol = question_19(input)
q19.check()

<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

## **Q20**: Time Series Data Transformation and Feature Engineering

### *Problem Statement:*  
You are given a time series dataset representing sensor readings from multiple devices. Each row consists of sensor values at a specific timestamp. Your task is to preprocess and extract meaningful features from the dataset by performing the following transformations:

### *Steps to Follow:*
1. Normalize Each Sensor Reading  
- Subtract the mean and divide by the standard deviation for each column.  
- Avoid division by zero by replacing std=0 with 1.  
2. Detect and Mask Anomalous Values
- If a sensor reading is more than 2.5 standard deviations away from the mean, replace it with NaN.
3. Interpolate Missing Values (NaN Handling)
- Fill NaN values with the average of the nearest non-NaN neighbors.
4. Extract First-Order Differences
- Compute the difference between consecutive time steps for each sensor.
5. Add a Binary Column for Missing Data
- Stack All Features into a Final Matrix
Create a new column `missing_flag` that is `1` where original data was `NaN`, otherwise `0`.
6. Stack All Features into a Final Matrix
- The final dataset should have normalized values, moving averages, first-order differences, and the missing flag.

In [86]:
import pandas as pd
input = np.array(
    [
        [1.0, 10.0, 100.0],
        [2.0, 20.0, 200.0],
        [3.0, 30.0, 10000.0],  # Outlier in third column
        [4.0, 40.0, 400.0],
        [5.0, 50.0, 500.0],
    ]
)


def question_20(input):
    df = pd.DataFrame(input)

    # Step 1: Compute mean/std on original data
    means = df.mean()
    stds = df.std()
    z_scores = (df - means) / stds

    # Step 2: Mask outliers (> 2.5 std dev) with NaN
    outlier_mask = np.abs(z_scores) > 2.5
    df_masked = df.mask(outlier_mask)

    # Step 3: Save missing flag (where original value was masked)
    missing_flag = outlier_mask.astype(int)

    # Step 4: Fill NaNs with average of nearest non-NaN neighbors
    df_filled = df_masked.copy()
    for col in df_filled.columns:
        for i in range(len(df_filled)):
            if pd.isna(df_filled.at[i, col]):
                # Look left
                left = df_filled.loc[:i-1, col][~df_filled.loc[:i-1, col].isna()]
                # Look right
                right = df_filled.loc[i+1:, col][~df_filled.loc[i+1:, col].isna()]
                neighbors = []
                if not left.empty:
                    neighbors.append(left.iloc[-1])
                if not right.empty:
                    neighbors.append(right.iloc[0])
                if neighbors:
                    df_filled.at[i, col] = np.mean(neighbors)

    # Step 5: Normalize filled values
    df_normalized = (df_filled - means) / stds

    # Step 6: First-order differences
    df_diff = df_normalized.diff().fillna(0)

    # Step 7: Stack final matrix
    final_matrix = np.hstack([
        df_normalized.to_numpy(),
        df_diff.to_numpy(),
        missing_flag.to_numpy()
    ])

    return final_matrix


q20_sol = question_20(input)
q20.check()

<IPython.core.display.Javascript object>

<span style="color:#cc3333">Incorrect:</span> Incorrect value for `q20_sol`: `array([[-1.26491106, -1.26491106, -0.49299073,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [-0.63245553, -0.63245553, -0.46995378,  0.63245553,  0.63245553,
         0.02303695,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.7876673 ,  0.63245553,  0.63245553,
         2.25762108,  0.        ,  0.        ,  0.        ],
       [ 0.63245553,  0.63245553, -0.42387988,  0.63245553,  0.63245553,
        -2.21154718,  0.        ,  0.        ,  0.        ],
       [ 1.26491106,  1.26491106, -0.40084293,  0.63245553,  0.63245553,
         0.02303695,  0.        ,  0.        ,  0.        ]])`